/*
  # ClaimStream AI - Patent Drafting Schema

  ## Overview
  Schema for the ClaimStream AI patent drafting application. Stores patent drafting
  sessions, clarifying questions/answers, and generated patent claims.

  ## Tables

  ### patent_sessions
  - Tracks each patent drafting session from technical description to final claims
  - Stores the original technical description, session state, and invention metadata

  ### session_questions
  - Stores the clarifying questions generated by the AI for each session
  - Tracks user answers to enable accurate claim generation

  ### patent_drafts
  - Stores the generated patent documents including abstract, background,
    summary, and claims sections

  ## Security
  - RLS enabled on all tables
  - Authenticated users can only access their own sessions
  - Public read is disabled; all access requires authentication
*/

-- Patent drafting sessions
CREATE TABLE IF NOT EXISTS patent_sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  title text NOT NULL DEFAULT '',
  technical_description text NOT NULL DEFAULT '',
  invention_type text NOT NULL DEFAULT 'mechanical',
  status text NOT NULL DEFAULT 'questioning',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE patent_sessions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own sessions"
  ON patent_sessions FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own sessions"
  ON patent_sessions FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own sessions"
  ON patent_sessions FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own sessions"
  ON patent_sessions FOR DELETE
  TO authenticated
  USING (auth.uid() = user_id);

-- Clarifying questions and answers
CREATE TABLE IF NOT EXISTS session_questions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id uuid REFERENCES patent_sessions(id) ON DELETE CASCADE NOT NULL,
  question_number integer NOT NULL,
  question_text text NOT NULL DEFAULT '',
  answer_text text NOT NULL DEFAULT '',
  category text NOT NULL DEFAULT 'general',
  created_at timestamptz DEFAULT now()
);

ALTER TABLE session_questions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own session questions"
  ON session_questions FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM patent_sessions
      WHERE patent_sessions.id = session_questions.session_id
      AND patent_sessions.user_id = auth.uid()
    )
  );

CREATE POLICY "Users can insert own session questions"
  ON session_questions FOR INSERT
  TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM patent_sessions
      WHERE patent_sessions.id = session_questions.session_id
      AND patent_sessions.user_id = auth.uid()
    )
  );

CREATE POLICY "Users can update own session questions"
  ON session_questions FOR UPDATE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM patent_sessions
      WHERE patent_sessions.id = session_questions.session_id
      AND patent_sessions.user_id = auth.uid()
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM patent_sessions
      WHERE patent_sessions.id = session_questions.session_id
      AND patent_sessions.user_id = auth.uid()
    )
  );

-- Generated patent drafts
CREATE TABLE IF NOT EXISTS patent_drafts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id uuid REFERENCES patent_sessions(id) ON DELETE CASCADE NOT NULL UNIQUE,
  abstract_text text NOT NULL DEFAULT '',
  background_text text NOT NULL DEFAULT '',
  summary_text text NOT NULL DEFAULT '',
  brief_drawings_text text NOT NULL DEFAULT '',
  detailed_description_text text NOT NULL DEFAULT '',
  claims_text text NOT NULL DEFAULT '',
  independent_claims jsonb NOT NULL DEFAULT '[]',
  dependent_claims jsonb NOT NULL DEFAULT '[]',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE patent_drafts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own patent drafts"
  ON patent_drafts FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM patent_sessions
      WHERE patent_sessions.id = patent_drafts.session_id
      AND patent_sessions.user_id = auth.uid()
    )
  );

CREATE POLICY "Users can insert own patent drafts"
  ON patent_drafts FOR INSERT
  TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM patent_sessions
      WHERE patent_sessions.id = patent_drafts.session_id
      AND patent_sessions.user_id = auth.uid()
    )
  );

CREATE POLICY "Users can update own patent drafts"
  ON patent_drafts FOR UPDATE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM patent_sessions
      WHERE patent_sessions.id = patent_drafts.session_id
      AND patent_sessions.user_id = auth.uid()
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM patent_sessions
      WHERE patent_sessions.id = patent_drafts.session_id
      AND patent_sessions.user_id = auth.uid()
    )
  );

-- Index for performance
CREATE INDEX IF NOT EXISTS idx_patent_sessions_user_id ON patent_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_session_questions_session_id ON session_questions(session_id);
CREATE INDEX IF NOT EXISTS idx_patent_drafts_session_id ON patent_drafts(session_id);
